NOT WORKING
adde capella integration tests

- Please note that integration testing is not working on Windows at all (tasks.py will error out with the clean task not finding *.scripts).
- Under Linux, there is an issue with the modified reqif version that is not installed via poetry and the git repo dev version of reqif will not be used by strictdoc, which make the test fail
- Under Linux, the test generating html output does not work because of a TextX error (Note: html export is working when done manually under Windows!):
  TextXSyntaxError: None:79:11: error: Expected '
' at position /app/contrib/strictdoc/tests/integration/commands/export/html/requirements_coverage/10_WIP/output.sdoc:(79, 11) => '[/SECTION]*'.